// Tests for the shared-core full-pipeline orchestrator (ADR 0005, issue #57).
//
// The compiled core artifact is never committed, so this test rebuilds it the
// same way scripts/lib/core-artifact.mjs does and imports
// obsidian-plugin/dist/core.mjs directly. Every effect (LLM HTTP calls, QMD
// query execution, vault realpath, note reads) is injected through fakes, so
// this test never touches the network or a real vault.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import path from "node:path";
import test from "node:test";
import { pathToFileURL } from "node:url";

const repoRoot = path.resolve(import.meta.dirname, "..", "..", "..", "..");
const pluginDir = path.join(repoRoot, "obsidian-plugin");
const artifactPath = path.join(pluginDir, "dist", "core.mjs");

const build = spawnSync(process.execPath, ["esbuild.config.mjs", "core"], {
  cwd: pluginDir,
  encoding: "utf-8",
});
if (build.error) {
  throw new Error(`core artifact build failed to spawn: ${build.error.message}`);
}
if (build.status !== 0) {
  throw new Error(`core artifact build failed (exit ${build.status}):\n${build.stdout ?? ""}${build.stderr ?? ""}`);
}

const core = await import(pathToFileURL(artifactPath).href);
const { runFullPipeline } = core;

const responsesEnvelope = (json) => ({
  status: 200,
  bodyText: JSON.stringify({ output_text: JSON.stringify(json) }),
});

const validPlanJson = {
  queries: ["raw", "abstracted_judgment", "contextual"].map((kind) => ({
    kind,
    command: "qmd query",
    text: `${kind} query`,
    qmd: {
      intent: `召回 ${kind} 相关的旧判断`,
      lex: ["反馈", "闭环", "学习", "改进"],
      vec: "围绕反馈闭环和学习改进寻找旧判断。",
      hyde: "一篇旧笔记讨论反馈如何帮助学习改进。",
    },
  })),
};

function judgeSuccessJson(relation) {
  return {
    ok: true,
    sourcePath: "Source.md",
    generatedAt: null,
    summary: "Judged one candidate.",
    warnings: [],
    error: null,
    candidates: [
      {
        notePath: "Memory/Feedback.md",
        noteTitle: "Feedback",
        relation,
        hit: "\"Feedback loops expose experience gaps\"",
        why: "Feedback evidence connects the old note to the current source insight.",
        quotes: relation === "weak" ? [] : ["Feedback loops expose experience gaps"],
        selected: true,
      },
    ],
  };
}

const vaultNotes = {
  "/vault/Memory/Feedback.md": "---\ntitle: Feedback\n---\nFeedback loops expose experience gaps and help judgment improve.\n",
};

function baseDeps({ httpScript, qmdRows }) {
  let httpIndex = 0;
  return {
    httpPost: async () => {
      const step = httpScript[Math.min(httpIndex, httpScript.length - 1)];
      httpIndex += 1;
      if (step instanceof Error) throw step;
      return step;
    },
    sleep: async () => {},
    runQmdQuery: async () => JSON.stringify(qmdRows),
    path: {
      isAbsolute: (value) => path.isAbsolute(value),
      relative: (from, to) => path.relative(from, to),
      resolve: (...segments) => path.resolve(...segments),
      basename: (value, ext) => (ext === undefined ? path.basename(value) : path.basename(value, ext)),
    },
    posixNormalize: (value) => path.posix.normalize(value),
    realpath: async (absolutePath) => absolutePath,
    readNote: async (absolutePath) => {
      if (!(absolutePath in vaultNotes)) throw new Error(`ENOENT: ${absolutePath}`);
      return vaultNotes[absolutePath];
    },
  };
}

const args = {
  sourcePath: "Source.md",
  sourceText: "反馈闭环暴露经验差距，也帮助下一次行动修正。",
  id: "case-1",
  _resolved_insight_input: "反馈闭环暴露经验差距，也帮助下一次行动修正。",
  vaultRoot: "/vault",
  targetCandidates: 20,
};

const llm = {
  baseUrl: "https://api.openai.com/v1",
  apiKey: "sk-test",
  model: "gpt-test",
  protocol: "responses",
  timeoutMs: 60_000,
};

test("runs the full pipeline end to end and returns a successful aha-result", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope(judgeSuccessJson("supports"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, true);
  assert.equal(result.sourcePath, "Source.md");
  assert.equal(result.error, null);
  assert.equal(result.candidates.length, 1);
  assert.equal(result.candidates[0].notePath, "Memory/Feedback.md");
  assert.equal(result.candidates[0].relation, "supports");
  assert.ok(!("_rawLocations" in result.candidates[0]), "internal _rawLocations must be stripped from the final result");
  assert.match(result.summary, /LLM generated 3 QMD query rewrites/);
  assert.ok(result.warnings.some((warning) => warning.includes("Query plan generated by llm")));
});

test("returns a structured failure when QMD retrieval yields no usable candidates", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson)],
    qmdRows: [],
  });

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, false);
  assert.equal(result.candidates.length, 0);
  assert.equal(result.error.tool, "qmd");
  assert.match(result.error.message, /no usable candidates/);
});

test("returns a structured failure (never a fake success) when Relation Judge fails", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), new Error("relation judge network failure")],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, false);
  assert.equal(result.error.tool, "llm");
  assert.match(result.error.details, /failed relation judging/);
  // Candidates are still attached (weak, pre-judge) for diagnostics, exactly
  // like the legacy wrapper's failure shape -- but ok stays false.
  assert.equal(result.candidates.length, 1);
  assert.equal(result.candidates[0].notePath, "Memory/Feedback.md");
  assert.ok(result.warnings.some((warning) => warning.includes("Relation Judge unavailable")));
});

test("falls back to the deterministic rules query plan when the planning LLM call fails, and still completes", async () => {
  const deps = baseDeps({
    httpScript: [new Error("query plan network failure"), responsesEnvelope(judgeSuccessJson("weak"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, true);
  assert.ok(result.warnings.some((warning) => warning.includes("Query plan generated by rules after fallback")));
});

// --- Prompt override threading (issue #59) ----------------------------------
// args.queryPromptOverride is additive: every test above omits it and must
// keep behaving exactly as before (already verified since those tests are
// unmodified). These tests cover the threading itself.

test("without queryPromptOverride, the result records the built-in query-plan prompt version", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope(judgeSuccessJson("supports"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.queryPlanGeneratedBy, "llm");
  assert.equal(result.queryPlanFallback, false);
  assert.equal(result.queryPlanPromptVersion, "aha-query-plan-v7");
});

// --- Obsidian graph expansion (ADR 0005 follow-up) --------------------------
// deps.listGraphNeighbors is optional and additive: every test above omits it
// and keeps behaving exactly as before (already verified since those tests
// are unmodified).

test("deps.listGraphNeighbors is optional; omitting it changes nothing", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope(judgeSuccessJson("supports"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });
  assert.equal(deps.listGraphNeighbors, undefined);

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, true);
  assert.equal(result.candidates.length, 1);
});

test("graph-expansion neighbors merge into the candidate pool alongside QMD retrieval", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope({
      ok: true,
      sourcePath: "Source.md",
      generatedAt: null,
      summary: "Judged two candidates.",
      warnings: [],
      error: null,
      candidates: [
        judgeSuccessJson("supports").candidates[0],
        {
          notePath: "Memory/Linked.md",
          noteTitle: "Linked",
          relation: "weak",
          hit: "Linked via outlink",
          why: "Neighborhood signal only.",
          quotes: [],
          selected: true,
        },
      ],
    })],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });
  vaultNotes["/vault/Memory/Linked.md"] = "Linked note body with enough substantive text to pass the excerpt filter.";
  deps.listGraphNeighbors = async (sourcePath) => {
    assert.equal(sourcePath, "Source.md");
    return { neighbors: [{ notePath: "Memory/Linked.md", kind: "outlink" }], warnings: [] };
  };

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, true);
  const paths = result.candidates.map((candidate) => candidate.notePath);
  assert.ok(paths.includes("Memory/Linked.md"), "graph-expansion neighbor should reach the final candidate set");
});

test("a listGraphNeighbors failure surfaces as a warning without failing the pipeline", async () => {
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope(judgeSuccessJson("supports"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });
  deps.listGraphNeighbors = async () => {
    throw new Error("obsidian CLI not found");
  };

  const result = await runFullPipeline(args, llm, deps);

  assert.equal(result.ok, true);
  assert.ok(result.warnings.some((warning) => warning.includes("Obsidian graph expansion failed: obsidian CLI not found")));
});

test("args.queryPromptOverride threads through to the query-plan LLM call and is recorded on the result", async () => {
  let capturedInput;
  const deps = baseDeps({
    httpScript: [responsesEnvelope(validPlanJson), responsesEnvelope(judgeSuccessJson("supports"))],
    qmdRows: [{ file: "Memory/Feedback.md", title: "Feedback", snippet: "Feedback loops expose experience gaps", score: 0.9 }],
  });
  const originalHttpPost = deps.httpPost;
  deps.httpPost = async (url, headers, body, timeoutMs) => {
    if (capturedInput === undefined) capturedInput = JSON.parse(body).input;
    return originalHttpPost(url, headers, body, timeoutMs);
  };

  const overrideArgs = {
    ...args,
    queryPromptOverride: { text: "CUSTOM ORCHESTRATOR OVERRIDE PROMPT", version: "aha-query-plan-custom-orchestratortest" },
  };
  const result = await runFullPipeline(overrideArgs, llm, deps);

  assert.equal(result.ok, true);
  assert.equal(capturedInput, "CUSTOM ORCHESTRATOR OVERRIDE PROMPT");
  assert.equal(result.queryPlanPromptVersion, "aha-query-plan-custom-orchestratortest");
});
